import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Fragment } from 'react'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className="min-h-full">
              <div className="py-10">
                  <main>
                      <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">{children}</div>
                  </main>
              </div>
          </div>
      </body>
    </html>
  );
}
